Post db model
GXLDSTEIN/bestnews_demo pull request #12
Opened 2023-12-28 20:01 UTC by Patsiomkina888

Created a post model, set up db config

2023-12-28 21:16 UTC, Chyrets requested changes

2023-12-28 21:16 UTC, Chyrets commented on bestnews_demo/model.py
> +    author = db.Column(db.String, nullable=True)
может тут лучше False? так как у любой статьи по идее должен быть автор

2023-12-28 21:16 UTC, Chyrets commented on bestnews_demo/model.py
> +    created_at = db.Column(db.DateTime, nullable=False)
Вот тут лучше сделать так, чтобы при создании записи дата автоматически выставлялась

2023-12-29 09:44 UTC, Patsiomkina888 commented on bestnews_demo/model.py
> +    author = db.Column(db.String, nullable=True)
я вот тут и думала, что поставить, мысль была, что может  у новости, которую будем с других сайтов брать, не окажется автора. Но полагаю, будем брать с хороших сайтов и везде будет ок:)))

2023-12-29 09:44 UTC, Patsiomkina888 commented on bestnews_demo/model.py
> +    created_at = db.Column(db.DateTime, nullable=False)
спасибо , дополнила

2024-01-02 16:41 UTC, Patsiomkina888 commented on bestnews_demo/model.py
> +    created_at = db.Column(db.DateTime, nullable=False)
@Chyrets также исправила f-string (ранее было написано по старому формату)

2024-01-02 20:43 UTC, Chyrets approved these changes

2024-01-03 10:00 UTC, merged