Created route to all posts pages by category
GXLDSTEIN/bestnews_demo pull request #6
Opened 2023-12-19 15:51 UTC by Patsiomkina888

- added route to posts by category;
- added some information in data for better testing
- added get_posts() (function)
- added html for rendering posts pages (posts_page.html)
- fixes styles for headings in styles.css

2023-12-19 17:29 UTC, Chyrets requested changes

2023-12-19 17:29 UTC, Chyrets commented on bestnews_demo/__init__.py
> +            return f"Error: {e}"
тут лучше сделать через параметры и не делать поле category обязательным: если ничего не переданно, то возвращаются все посты, если передат какой-то параметр, то пытаемся из бд взять посты по этому параметру
Вот тут есть то, как достать параметр из запроса
https://stackoverflow.com/questions/24892035/how-can-i-get-the-named-parameters-from-a-url-using-flask

2023-12-19 17:29 UTC, Chyrets commented on bestnews_demo/__init__.py
> +            return f"Error: {e}"
так же лучше не возвращать вот так ошибку, в таком случае лучше возвращать одну из 400х ошибок

2023-12-20 08:20 UTC, GXLDSTEIN commented on bestnews_demo/__init__.py
> +            if category == "it_news":
Здесь же _хорошее_ место для [match/case](https://docs.python.org/3/tutorial/controlflow.html#tut-match)?

2023-12-20 14:56 UTC, Chyrets requested changes

2023-12-20 14:56 UTC, Chyrets commented on bestnews_demo/__init__.py
> +                abort(400, "Invalid category")
убери эти все ифы и сделай примерно так context.get(category, [])

2023-12-20 14:56 UTC, Chyrets commented on bestnews_demo/__init__.py
> +        context = get_posts()
вот тут замени лучше имя context на posts

2023-12-20 15:11 UTC, Patsiomkina888 commented on bestnews_demo/__init__.py
> +        context = get_posts()
я сделала вот так так как context - это словарь, и просто заменить его в функции рабоать не будет. : def all_posts():
        posts = []
        for _, news in get_posts().items():
            posts.extend(news)
        title = "All News"
        headline = "Latest News from all categories"
        return render_template(
            "posts_page.html", posts=posts, title=title, headline=headline
        )    

подойдет так?

2023-12-20 15:11 UTC, Patsiomkina888 commented on bestnews_demo/__init__.py
> +                abort(400, "Invalid category")
@Chyrets    подскажи, пожалуйста, как это повлияет на код?  может я не понимаю, как использовать эту функцию, так как у меня же еще для каждой категории идет отдельно title  и headline

2023-12-20 15:27 UTC, Chyrets requested changes

2023-12-20 15:27 UTC, Chyrets commented on bestnews_demo/__init__.py
> +        context = get_posts()
тут не критично, но лучше просто поменять имя перемнной с context на другое, так как часто переменная с именем context создается для render_template
https://tedboy.github.io/flask/generated/flask.render_template.html

2023-12-20 15:27 UTC, Chyrets commented on bestnews_demo/__init__.py
> +                abort(400, "Invalid category")
тут надо тогда сделать 2 словаря для title и headline (TITLES, HEADLINES) и по ним брать нужное тебе значение, так как получается что количество категорий у нас ограниченно имеет смысл завернуть это все в блок try/except и если нету нужного значения в этих словарях, то возвращаться 404 ошибку

2023-12-20 15:27 UTC, Chyrets commented on bestnews_demo/__init__.py
> +                abort(400, "Invalid category")
так же лучше сделать константы для этих категорий, все это можешь добавитьв файл constants.py

2023-12-21 11:07 UTC, Patsiomkina888 commented on bestnews_demo/__init__.py
> +                abort(400, "Invalid category")
@Chyrets  посмотри, пожалуйста, последний коммит. У меня не получилось убрать совсем if, и поставить try/except, так как есть отдельное первое улсовие, когда передаем без категории, и затем проверяем, есть ли такая категория в базе. Можешь подсказать, как лучше тогда добавить try/except, чтобы можно было сохранить поочередность показа ошибок? (у меня не получается дойти до 404, если передаю неверную категорию, так как в TITLES.get(category) вернет None (ну или поставит title, headline дефолтное, если кажу)

2023-12-21 16:19 UTC, Chyrets commented on bestnews_demo/__init__.py
> +    @app.route("/all_posts")
а почему тут дуюлируется эта строка?

2023-12-21 16:21 UTC, Chyrets commented on bestnews_demo/__init__.py
> +            if category == "it_news":
Скорее нет чем да, тут просто сравниваются строки, а в питоне match обычно используется для более сложных сравнений

2023-12-21 16:22 UTC, Patsiomkina888 commented on bestnews_demo/__init__.py
> +    @app.route("/all_posts")
@Chyrets Сорри, это ошибка, исправлю

2023-12-21 16:55 UTC, Patsiomkina888 commented on bestnews_demo/__init__.py
> +    @app.route("/all_posts")
исправила: https://github.com/GXLDSTEIN/bestnews_demo/pull/6/commits/0dc0fffc06659fc42586cfc3cdd998a490cde294

2023-12-21 16:57 UTC, Chyrets approved these changes

2023-12-21 19:40 UTC, merged